#This pulls data from AWS and creates a Kubernetes Secret automatically:
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: my-db-secret
  namespace: default
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secret-store
    kind: SecretStore
  target:
    name: db-secret   # Kubernetes Secret name
    creationPolicy: Owner
  data:
    - secretKey: username
      remoteRef:
        key: my-db-secret
        property: username

    - secretKey: password
      remoteRef:
        key: my-db-secret
        property: password
        
  apiVersion: external-secrets.io/v1beta1 
  kind: ExternalSecreat
  metadata: 
    name: External-secreat 
    namespace: default 
  spec: 
    refreshInterval: 1h 
